[versions]
junit-jupiter = "6.0.1"
hamcrest = "3.0"
byte-buddy = "1.18.3"
jmock = "2.13.1"
easymock = "5.6.0"
mockito= "5.21.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
jmock-junit5 = { module = "org.jmock:jmock-junit5", version.ref = "jmock" }
jmock-imposters = { module = "org.jmock:jmock-imposters", version.ref = "jmock" }
easymock = { module = "org.easymock:easymock", version.ref = "easymock" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[bundles]
jmock = ["byte-buddy", "jmock-junit5", "jmock-imposters"]
